import os
import csv
import math
import random
import argparse
import subprocess
from pathlib import Path
from PIL import Image
from tqdm import tqdm

# ==========================================
# Configuration
# ==========================================
LBM_EXECUTABLE = "./solver"  # Change to "solver.exe" on Windows
DATASET_DIR = Path("dataset")
IMAGES_DIR = DATASET_DIR / "images"
MASTER_CSV = DATASET_DIR / "training_data.csv"

# Domain size
NX = 400
NY = 100

# Subprocess timeout (seconds) to prevent infinite hangs
TIMEOUT = 60 

# ==========================================
# Helper Functions
# ==========================================
def setup_directories():
    """Create necessary directories and initialize the master CSV."""
    IMAGES_DIR.mkdir(parents=True, exist_ok=True)
    
    # Initialize master CSV with headers if it doesn't exist
    if not MASTER_CSV.exists():
        with open(MASTER_CSV, mode='w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow([
                "sample_id", "shape", "size1", "size2", 
                "angle", "velocity", "Cd", "pressure_loss", "image_path"
            ])

def cleanup_temp_files():
    """Remove temporary files generated by the C++ solver to avoid cross-contamination."""
    temp_files = ["results.csv", "flow_field.ppm"]
    for f in temp_files:
        if os.path.exists(f):
            os.remove(f)

def generate_random_params(allowed_shapes):
    """Generate random physical parameters for the CFD simulation."""
    shape = random.choice(allowed_shapes)
    
    # Scale sizes to fit within the NY=100 domain without blocking the flow completely
    # Max height should ideally be < 40% of the channel height (NY)
    max_size = NY * 0.35 
    min_size = NY * 0.05
    
    size1 = random.uniform(min_size, max_size)
    
    if shape == "circle":
        size2 = size1  # Circle only uses radius (size1), but we keep size2 consistent
    else:
        size2 = random.uniform(min_size, max_size)
        
    angle = random.uniform(0.0, 180.0)
    velocity = random.uniform(0.02, 0.1)
    
    return {
        "shape": shape,
        "size1": round(size1, 3),
        "size2": round(size2, 3),
        "angle": round(angle, 2),
        "velocity": round(velocity, 4)
    }

# ==========================================
# Main Automation Loop
# ==========================================
def main():
    parser = argparse.ArgumentParser(description="Automate CFD Data Generation")
    parser.add_argument("--samples", type=int, default=1000, help="Number of samples to generate")
    parser.add_argument("--shapes", type=str, nargs='+', choices=['circle', 'rect', 'tri'], 
                        default=['circle', 'rect', 'tri'], 
                        help="List of shapes to generate (e.g., --shapes circle rect)")
    args = parser.parse_args()
    
    num_samples = args.samples
    allowed_shapes = args.shapes

    if not os.path.exists(LBM_EXECUTABLE):
        print(f"Error: Executable '{LBM_EXECUTABLE}' not found. Please compile the C++ code first.")
        return

    setup_directories()
    
    successful_samples = 0
    
    print(f"Starting CFD data generation for {num_samples} samples using shapes: {', '.join(allowed_shapes)}...")
    
    with tqdm(total=num_samples, desc="Generating Dataset") as pbar:
        while successful_samples < num_samples:
            # 1. Generate Parameters
            params = generate_random_params(allowed_shapes)
            
            # 2. Cleanup old runs
            cleanup_temp_files()
            
            # 3. Build CLI command
            cmd = [
                LBM_EXECUTABLE,
                "--width", str(NX),
                "--height", str(NY),
                "--shape", params["shape"],
                "--size1", str(params["size1"]),
                "--size2", str(params["size2"]),
                "--angle", str(params["angle"]),
                "--velocity", str(params["velocity"]),
                "--steps", "15000" # Give it enough steps to reach steady state
            ]
            
            # 4. Run the C++ Solver
            try:
                # Capture output to keep console clean, enforce timeout
                subprocess.run(cmd, capture_output=True, text=True, timeout=TIMEOUT, check=True)
            except subprocess.TimeoutExpired:
                # Ignore this iteration and retry
                continue
            except subprocess.CalledProcessError:
                # C++ solver crashed or returned non-zero
                continue
                
            # 5. Verify and Read Output
            if not os.path.exists("results.csv") or not os.path.exists("flow_field.ppm"):
                continue # Missing output files, retry
                
            try:
                # The C++ script appends to results.csv and writes a header if new.
                # Since we delete it before every run, it will exactly have 2 lines: Header + Data
                with open("results.csv", mode='r') as f:
                    reader = csv.DictReader(f)
                    row = next(reader)
                    
                Cd = float(row["Cd"])
                dP = float(row["pressure_loss"])
                
                # 6. NaN / Inf Check
                if math.isnan(Cd) or math.isinf(Cd) or math.isnan(dP) or math.isinf(dP):
                    continue # Discard unstable numerical results
                    
                # Optional: Discard physically unrealistic blow-ups (e.g. Cd > 100)
                if abs(Cd) > 100.0:
                    continue
                    
            except (ValueError, StopIteration, KeyError):
                # Corrupted CSV output
                continue
                
            # 7. Process Image (PPM -> PNG)
            sample_id = f"{successful_samples:05d}"
            image_filename = f"sample_{sample_id}.png"
            image_filepath = IMAGES_DIR / image_filename
            
            try:
                with Image.open("flow_field.ppm") as img:
                    img.save(image_filepath, format="PNG")
            except Exception:
                # Corrupted image file
                continue
                
            # 8. Append to Master CSV
            with open(MASTER_CSV, mode='a', newline='') as f:
                writer = csv.writer(f)
                writer.writerow([
                    sample_id, 
                    params["shape"], 
                    params["size1"], 
                    params["size2"], 
                    params["angle"], 
                    params["velocity"], 
                    Cd, 
                    dP, 
                    str(image_filepath.as_posix())
                ])
                
            # 9. Finalize Iteration
            successful_samples += 1
            pbar.update(1)

    # Final cleanup
    cleanup_temp_files()
    print(f"\nDataset successfully generated at: {DATASET_DIR.absolute()}")

if __name__ == "__main__":
    main()
